{
 "title": "NATS Client Connection Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "NATS Clients Msgs In",
   "type": "graph",
   "description": "The number of incoming messages separated out by client connection",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatds_clients_in_msgs_total", "legendFormat": "{{clientname}}" }
   ]
  },
  {
   "title": "NATS Clients Msgs Out",
   "type": "graph",
   "description": "The number of outgoing messages separated out by client connection",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatds_clients_out_msgs_total", "legendFormat": "{{clientname}}" }
   ]
  },
  {
   "title": "NATS Clients Bytes In",
   "type": "graph",
   "description": "The number of incoming bytes separated out by client connection",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatds_clients_in_bytes_total", "legendFormat": "{{clientname}}" }
   ]
  },
  {
   "title": "NATS Clients Bytes Out",
   "type": "graph",
   "description": "The number of outgoing bytes separated out by client connection",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatds_clients_out_bytes_total", "legendFormat": "{{clientname}}" }
   ]
  },
  {
   "title": "NATS Clients Pending Bytes",
   "type": "graph",
   "description": "The number of pending bytes separated out by client connection",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gnatds_clients_pending_bytes_total",
     "legendFormat": "{{clientname}}"
    }
   ]
  },
  {
   "title": "NATS Clients Bytes Out",
   "type": "graph",
   "description": "The number of outgoing bytes separated out by client connection",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gnatds_clients_subscriptions_total",
     "legendFormat": "{{clientname}}"
    }
   ]
  }
 ]
}